#!/bin/bash
#

display_usage() {
	echo "At lest 1 arguments are required"
}

if [  $# != 1 ]
then
    display_usage
    exit 1
fi

TITLE=$1
_fname="${TITLE// /_}"
FILENAME="`date "+%Y-%m-%d"`-$_fname.md"
SNIP="---
title : \"$TITLE\"
#excerpt : \"\"

categories:
   - Blog
tags:
   - Blog
---

"
echo "$SNIP" | tr -s '[:blank:]'
echo "$SNIP"  > $FILENAME

echo "Do something great!!"
