#!/bin/bash
#

display_usage() {
	echo "At lest 1 arguments are required"
}

if [  $# != 1 ]
then
    display_usage
    exit 1
fi

FILENAME="`date "+%Y-%m-%d"`-$1.md"
SNIP="---
title : \"Android source Version check\"
#excerpt : \"\"

categories:
   - Blog
tags:
   - Blog
---
New Post 새로운 시작
"
echo "$SNIP" | tr -s '[:blank:]'
echo "$SNIP"  > $FILENAME

echo "Do something great!!"
